import { getFinancialTransactions } from '@/lib/financial/financial-actions';
const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
export default async function CashFlowPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const params=await searchParams;
  const result=await getFinancialTransactions({ type: params.type || undefined, status: params.status || undefined, startDate: params.startDate, endDate: params.endDate });
  if(!result.success) throw new Error(result.error);
  const rows=result.data??[];
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Fluxo de caixa</h1><p className="text-sm text-muted-foreground">Fonte oficial: FinancialTransaction.</p></div><form className="flex flex-wrap gap-3 rounded-lg border p-4"><input className="rounded border p-2" type="date" name="startDate" defaultValue={params.startDate}/><input className="rounded border p-2" type="date" name="endDate" defaultValue={params.endDate}/><select className="rounded border p-2" name="status" defaultValue={params.status??''}><option value="">Todos</option>{['PENDING','PAID','CANCELLED'].map(v=><option key={v}>{v}</option>)}</select><button className="rounded bg-primary px-4 text-primary-foreground">Filtrar</button></form><div className="overflow-x-auto rounded-lg border"><table className="min-w-[800px] w-full text-sm"><thead><tr className="bg-muted">{['Data','Descrição','Direção','Status','Conta','Valor'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(tx=><tr key={tx.id} className="border-t"><td className="p-3">{new Date(tx.createdAt).toLocaleDateString('pt-BR')}</td><td className="p-3">{tx.description}</td><td className="p-3">{tx.direction}</td><td className="p-3">{tx.status}</td><td className="p-3">{tx.bankAccount?.name??'—'}</td><td className="p-3 font-medium">{money(Number(tx.amount))}</td></tr>)}</tbody></table></div></div>;
}
