import { revalidatePath } from 'next/cache';
import { archiveProductVariant, createProductVariant, getProducts, getProductVariants, updateVariant } from '@/lib/crm/products-actions';

async function create(fd:FormData){'use server';await createProductVariant(String(fd.get('productId')),{name:String(fd.get('name')),sku:String(fd.get('sku')),barcode:String(fd.get('barcode')??'')||null,costPrice:Number(fd.get('costPrice')??0),salePrice:Number(fd.get('salePrice')??0),minimumStock:Number(fd.get('minimumStock')??0)});revalidatePath('/grades-variacoes');}
async function update(fd:FormData){'use server';await updateVariant(String(fd.get('id')),{name:String(fd.get('name')),sku:String(fd.get('sku')),barcode:String(fd.get('barcode')??'')||null,salePrice:Number(fd.get('salePrice')),minimumStock:Number(fd.get('minimumStock'))});revalidatePath('/grades-variacoes');}
async function archive(fd:FormData){'use server';await archiveProductVariant(String(fd.get('id')));revalidatePath('/grades-variacoes');}

export default async function VariantsPage(){
  const [variants,products]=await Promise.all([getProductVariants(),getProducts({page:1,pageSize:100})]);
  if(!variants.success||!products.success)throw new Error(variants.error??products.error);
  const productRows=(products as any).data?.data??[];
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Grades e variações</h1><p className="text-sm text-muted-foreground">Fonte canônica: ProductVariant. Nome pode representar tamanho e cor; SKU permanece único no tenant.</p></div>
    <form action={create} className="grid gap-3 rounded-lg border p-4 md:grid-cols-4"><select className="rounded border p-2" name="productId" required><option value="">Produto</option>{productRows.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="rounded border p-2" name="name" placeholder="Variação (ex.: Azul / 38)" required/><input className="rounded border p-2" name="sku" placeholder="SKU" required/><input className="rounded border p-2" name="barcode" placeholder="Código de barras"/><input className="rounded border p-2" name="costPrice" type="number" step="0.01" min="0" placeholder="Custo" required/><input className="rounded border p-2" name="salePrice" type="number" step="0.01" min="0" placeholder="Venda" required/><input className="rounded border p-2" name="minimumStock" type="number" step="0.01" min="0" placeholder="Estoque mínimo" defaultValue="0"/><button className="rounded bg-primary p-2 text-primary-foreground">Criar variação</button></form>
    <div className="space-y-3">{(variants.data??[]).map(row=><form action={update} key={row.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1.5fr_1fr_1fr_1fr_1fr_auto_auto]"><input type="hidden" name="id" value={row.id}/><label className="text-xs">{row.product.name}<input className="mt-1 w-full rounded border p-2" name="name" defaultValue={row.name}/></label><label className="text-xs">SKU<input className="mt-1 w-full rounded border p-2" name="sku" defaultValue={row.sku}/></label><label className="text-xs">Código<input className="mt-1 w-full rounded border p-2" name="barcode" defaultValue={row.barcode??''}/></label><label className="text-xs">Venda<input className="mt-1 w-full rounded border p-2" name="salePrice" type="number" step="0.01" min="0" defaultValue={Number(row.salePrice)}/></label><label className="text-xs">Mínimo<input className="mt-1 w-full rounded border p-2" name="minimumStock" type="number" step="0.01" min="0" defaultValue={Number(row.minimumStock)}/></label><button className="text-primary underline">Salvar</button><button formAction={archive} className="text-destructive underline">Inativar</button></form>)}</div>
  </div>;
}
